export interface Env {
  RUNNER_BACKEND?: 'actions-vm';
  RUNNER_ACTIONS_REPOSITORY?: string;
  RUNNER_ACTIONS_REPOSITORY_ID?: string;
  RUNNER_ACTIONS_REF?: string;
  RUNNER_ACTIONS_SHA?: string;
  RUNNER_ACTIONS_ORIGIN?: string;
  RUNNER_APP_ID?: string;
  RUNNER_APP_PRIVATE_KEY?: string;
  RUNNER_INSTALLATION_ID?: string;
  RUNNER?: DurableObjectNamespace;
  RUNNER_ENABLED?: string;
  RUNNER_ENDPOINT?: string;
  RUNNER_TUNNEL_KEY?: string;
  RUNNER_IMAGE_URI?: string;
  ORG_DB?: D1Database;
  ORG_SERVICE?: Fetcher;
  ORG_EVALUATOR?: Workflow<{ runId: string }>;
  ORG_NAME?: string;
  ORG_PUBLIC_ORIGIN?: string;
  ORG_REVIEW_ORIGINS?: string;
  ORG_ADMIN_TOKEN?: string;
  ORG_JUDGE_TOKEN?: string;
  ORG_SECURITY_TOKEN?: string;
  ORG_VAULT_KEY?: string;
  DB: D1Database;
  ARTIFACTS?: R2Bucket;
  ARTIFACT_KV?: KVNamespace;
  ASSETS: Fetcher;
  EVALUATOR: Workflow<{ runId: string }>;
  PREVIEW_EVALUATOR?: Workflow<{ runId: string }>;
  PREVIEW_TESTING?: string;
  AI?: Ai;
  ENVIRONMENT: 'local' | 'review' | 'production';
  DEMO_MODE?: string;
  ADMIN_TOKEN?: string;
  GITHUB_WEBHOOK_SECRET?: string;
  GITHUB_APP_ID?: string;
  GITHUB_APP_PRIVATE_KEY?: string;
  PUBLIC_ORIGIN?: string;
  EVALUATION_DETAILS_KIND?: 'organization';
  AI_PRICING_JSON?: string;
  AI_MODEL?: string;
  AI_MODEL_LIGHT?: string;
  AI_MODEL_DEEP?: string;
  AI_PROVIDER?: 'cloudflare' | 'callmissed' | 'gemini' | 'groq';
  GEMINI_API_KEY?: string;
  GEMINI_MODEL?: string;
  GEMINI_MODEL_LIGHT?: string;
  GEMINI_MODEL_DEEP?: string;
  GROQ_API_KEY?: string;
  GROQ_MODEL?: string;
  GROQ_MODEL_LIGHT?: string;
  GROQ_MODEL_DEEP?: string;
  CALLMISSED_API_KEY?: string;
  CALLMISSED_MODEL?: string;
  CALLMISSED_MODEL_LIGHT?: string;
  CALLMISSED_MODEL_DEEP?: string;
}
